### ISSUE TITLE
Spain location doesn't work anymore

### ISSUE THREAD

**Issue by indywidualny** [borys25ol/amazon-location-cookies-service#2]
I noticed ES location (as well as IT location however you don't support it here) stopped working.

```
➜  make docker_up

➜  curl http://127.0.0.1:8000/api/v1/cookies\?zip_code\=E1+6AN\&country_code\=UK
{"success":true,"data":{"zip_code":"E1 6AN","country_code":"UK","cookies":{"ubid-acbuk":"260-4203024-8393568","session-id-time":"2082758401l","lc-acbuk":"en_GB","session-id":"260-5857162-6594920"}},"message":null,"errors":[]}%

➜  curl http://127.0.0.1:8000/api/v1/cookies\?zip_code\=28010\&country_code\=ES
{"success":false,"status":404,"type":"CookiesNotFoundException","message":"Cookies for zip code: `28010` and region: `ES` not found","errors":[]}%
```

It seems to be caused by `CSRF_TOKEN` missing from `/gp/glow/get-address-selections.html?...` request response. Did you possibly find any solution to the issue?

**Comment by borys25ol** [comment]
Hi, thanks for your feedback.
I've provided some updates in this repository.
Italy region has been added, and Spain already should work.

**Comment by indywidualny** [comment]
Hello, possibly something could go wrong because `ubid-...` cookies are missing now.

```
➜  curl http://127.0.0.1:8000/api/v1/cookies\?zip_code\=10115\&country_code\=DE
{"success":true,"data":{"zip_code":"10115","country_code":"DE","cookies":{"session-id":"262-2885671-3592500","session-id-time":"2082787201l","i18n-prefs":"EUR","sp-cdn":"L5Z9:PL"}},"message":"Cookies for zip code: `10115` extracted successfully","errors":[]}%

➜  curl http://127.0.0.1:8000/api/v1/cookies\?zip_code\=28010\&country_code\=ES
{"success":true,"data":{"zip_code":"28010","country_code":"ES","cookies":{"session-id":"262-3232733-6685742","session-id-time":"2082787201l","i18n-prefs":"EUR"}},"message":"Cookies for zip code: `28010` extracted successfully","errors":[]}%
```

**Comment by borys25ol** [comment]
I don't even know what does this cookie mean.
Only one cookie needed for getting location content is `session-id`.

**Comment by indywidualny** [comment]
You're completely right. I thought the important ones are `ubid-...`, `session-id`, `session-id-time` but using only `session-id` is enough to localize results.

**Comment by indywidualny** [comment]
I'm looking at code changes and cannot fully understand what was the change which unlocked amazon.es in fact. I see CSRF token URL changed to a new one but the rest seems completely the same except some refactoring. I'm doing a similar script but with `aiohttp` and cannot make Spain working in fact. Constantly CSRF token is missing.

Could you tell me what was the real change which fixed Italy and Spain? Can be a link to a certain line in source code so I know where I should focus on.

**Comment by BorysOl** [comment]
The main problem was when parsing response headers after the first request to Amazon's main page.
I don't know why, but Amazon ES returns this list of cookies (raw response):
![image](https://user-images.githubusercontent.com/61782214/161306262-f78e5f29-0317-4d7c-a64d-3bdbca9b3c3f.png)

And my util `extract_response_cookies` (`main.utils`) parse this response as:
```
{
    'session-id': '-',
    'session-id-time': '-', 
    'i18n-prefs': 'EUR',
    'session-token': '-', 
    'ubid-acbes': '-',
    'at-acbes': '-',
    'lc-acbes': '-', 
    'x-acbes': '-', 
    'x-wl-uid': '-', 
    'sess-at-acbes': '-',
    'UserPref': '-'
}
```
And now after my fix, it looks like this:
```
{
    'session-id': '260-0572356-9277438', 
    'session-id-time':  '2082787201l',
    'i18n-prefs': 'EUR'
}
```
And as a result  - Amazon ES is working now.

**Comment by borys25ol** [comment]
The main problem was when parsing response headers after the first request to Amazon's main page.
I don't know why, but Amazon ES returns this list of cookies (raw response):
![image](https://user-images.githubusercontent.com/61782214/161306262-f78e5f29-0317-4d7c-a64d-3bdbca9b3c3f.png)

And my util `extract_response_cookies` (`main.utils`) parse this response as:
```
{
    'session-id': '-',
    'session-id-time': '-', 
    'i18n-prefs': 'EUR',
    'session-token': '-', 
    'ubid-acbes': '-',
    'at-acbes': '-',
    'lc-acbes': '-', 
    'x-acbes': '-', 
    'x-wl-uid': '-', 
    'sess-at-acbes': '-',
    'UserPref': '-'
}
```
And now after my fix, it looks like this:
```
{
    'session-id': '260-0572356-9277438', 
    'session-id-time':  '2082787201l',
    'i18n-prefs': 'EUR'
}
```
And as a result  - Amazon ES is working now.

**Comment by indywidualny** [comment]
Thx for help. Awesome 👍
