### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8

### ISSUE THREAD

**Issue by indywidualny** [borys25ol/amazon-location-cookies-service#9]
Im using your implementation and apparently it looks like Amazon changed something again:

`message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://www.amazon.it/portal-migration/hz/glow/address-change?actionSource=glow')`

After accepting HTML instead of json we can see 404 error:

```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
        <title>Impossibile trovare la pagina</title>

        <style type="text/css">
            a:link { font-family: verdana,arial,helvetica,sans-serif; color: #004B91; }
            a:visited { font-family: verdana,arial,helvetica,sans-serif; color: #996633; }
            a:active { font-family: verdana,arial,helvetica,sans-serif; color: #FF9933; }
        </style>
    </head>
    <body bgcolor="#FFFFFF" text="#000000" style="font-family: verdana,arial,helvetica,sans-serif;">
        <!--
            Per discutere dell’accesso automatico ai dati di Amazon contatta api-services-support@amazon.com

Per informazioni sulla migrazione alla nostra API consulta  la nostra API Marketplace qui https://developer.amazonservices.com/ref=rm_5_sv, o la nostra API di pubblicità prodotto qui https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html/ref=rm_5_ac per i casi d’uso pubblicitari.
        -->
        <center>
            <a href="/ref=cs_404_logo">
                <img src="https://images-eu.ssl-images-amazon.com/images/G/29/ShoppingPortal/logo._TTD_.png"
                     alt="Amazon" border="0"/>
            </a>
            <table border="0" align="center" style="margin-top: 20px;">
                <tr>
                    <td>
                        <img src="https://images-eu.ssl-images-amazon.com/images/G/29/x-locale/common/kailey-kitty._TTD_.gif" width="40" height="35" border="0">
                    </td>
                    <td>
                        <b style="color:#E47911">Cerchi qualcosa in particolare?</b>
                        <br/>
                        Siamo spiacenti. L'indirizzo web inserito non è una pagina funzionante sul nostro sito.
                        <br/><br/>
                        <img src="https://images-eu.ssl-images-amazon.com/images/G/29/x-locale/common/orange-arrow._TTD_.gif" width="10" height="9" border="0">
                        <b><a href="/ref=cs_404_link">Clicca qui per tornare alla home page di Amazon</a></b>
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html>
<!-- c6dc5ff8 -->
```

I will be investigating it but the script no longer works since few hours.

**Comment by indywidualny** [comment]
Looks like solution is to revert https://github.com/borys25ol/amazon-location-cookies-service/pull/7/files

Interesting. Maybe they decided to not to accept this change after all and revert to old mechanism.

**Comment by indywidualny** [comment]
Looks like a partial solution is to revert https://github.com/borys25ol/amazon-location-cookies-service/pull/7/files

Interesting. Maybe they decided to not to accept this change after all and revert to old mechanism for most domains.

It looks like www.amazon.co.uk and www.amazon.de don't work anymore no matter which URL used (for old one: `Host unreachable`, for new one the error from the issue). For the rest of them reverting recent changes does help.

It's very important to me to solve it quickly so any collaboration is appreciated. Currently I cannot figure out the right solution for those 2 remaining broken domains. Any ideas @yshalsager ?

**Comment by borys25ol** [comment]
For now, we should send a POST request with JSON body to change location, instead of sending a form-data request.
I've provided a fix, all countries are available to change the location at the moment.

**Comment by indywidualny** [comment]
Awesome! Solved indeed.
